env:
  node: true
  commonjs: true
  es6: true
parserOptions:
  sourceType: module
  ecmaVersion: 2017
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
extends:
  - 'eslint:recommended'
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console: off
  comma-dangle:
    - error
    - always-multiline
  react/jsx-uses-vars:
    - error
